

node('terraform'){

    /*parameters {
		string(name: 'AZURE_KEYVAULT_URL', description: 'Name of the image to build')
	}*/

    stage('test'){
        sh "terraform -version"
        sh "pwd"
        sh "ls -ll"
    }

    stage('Terraform Init'){        

        def secrets = [
            [ secretType: 'Secret', name: 'BACKEND_STORAGE_ACCOUNT_NAME', envVariable: 'BACKENDSTORAGE_ACCOUNTNAME' ],
            [ secretType: 'Secret', name: 'BACKEND_STORAGE_ACCOUNT_CONTAINER_NAME', envVariable: 'BACKENDSTORAGEACCOUNTCONTAINERNAME' ],
            [ secretType: 'Secret', name: 'RG_NAME', envVariable: 'RGNAME' ],
            [ secretType: 'Secret', name: 'ARM_ACCESS_KEY', envVariable: 'BACKENDACCESSKEY' ]
        ]

        withAzureKeyvault(
            azureKeyVaultSecrets: secrets, 
            keyVaultURLOverride: 'https://kv-devopsigb-prod-france.vault.azure.net/',
            credentialIDOverride: 'azure_service_principal'
        ) {
            sh 'echo $BACKENDSTORAGEACCOUNTNAME'
            sh 'echo $BACKENDSTORAGEACCOUNT_CONTAINERNAME'
            sh 'echo $RGNAME'
            sh 'echo $BACKENDACCESSKEY'
        }

    }
}