

node('terraform'){

    /*parameters {
		string(name: 'AZURE_KEYVAULT_URL', description: 'Name of the image to build')
	}*/

    stage('test'){
        sh "terraform -version"
        sh "pwd"
        sh "ls -ll"
    }

    stage('Terraform Init'){        

        def secrets = [
            [ secretType: 'Secret', name: 'BACKEND_STORAGE_ACCOUNT_NAME', envVariable: 'BACKEND_STORAGE_ACCOUNT_NAME' ],
            [ secretType: 'Secret', name: 'BACKEND_STORAGE_ACCOUNT_CONTAINER_NAME', envVariable: 'BACKEND_STORAGE_ACCOUNT_CONTAINER_NAME' ],
            [ secretType: 'Secret', name: 'RG_NAME', envVariable: 'RG_NAME' ],
            [ secretType: 'Secret', name: 'ARM_ACCESS_KEY', envVariable: 'BACKEND-ACCESS-KEY' ]
        ]

        withAzureKeyvault(secrets) {
            sh 'echo $BACKEND_STORAGE_ACCOUNT_NAME'
            sh 'echo $BACKEND_STORAGE_ACCOUNT_CONTAINER_NAME'
            sh 'echo $RG_NAME'
            sh 'echo $BACKEND-ACCESS-KEY'
        }

    }
}